// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3TEcFzM0T3k72Mj8QJHHiumaEOWTCNpA',
    appId: '1:882781148594:web:aafa3956ed0ad7c82480ab',
    messagingSenderId: '882781148594',
    projectId: 'minigames-uts',
    authDomain: 'minigames-uts.firebaseapp.com',
    storageBucket: 'minigames-uts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEc7j9sxyEBymCzza9wwcfbmOhmltjzm4',
    appId: '1:882781148594:android:28f7018e3bd314de2480ab',
    messagingSenderId: '882781148594',
    projectId: 'minigames-uts',
    storageBucket: 'minigames-uts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvJXMHa5WVg2g3YCofZWQ1wRxd8S4qvw',
    appId: '1:882781148594:ios:a354f68cbe876cf42480ab',
    messagingSenderId: '882781148594',
    projectId: 'minigames-uts',
    storageBucket: 'minigames-uts.firebasestorage.app',
    iosBundleId: 'com.example.miniGames',
  );
}
